const SET_CURRENT_USER = 'SET_CURRENT_USER'
const UPDATE_USERNAME_FORM = "UPDATE_USERNAME_FORM"
const TOGGLE_DELETE_ALERT = "TOGGLE_DELETE_ALERT"
const SET_CURRENT_CLIENT = 'SET_CURRENT_CLIENT'
const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
const RESET_CURRENT_CLIENT = 'RESET_CURRENT_CLIENT'

export {
    SET_CURRENT_USER,
    UPDATE_USERNAME_FORM,
    TOGGLE_DELETE_ALERT,
    SET_CURRENT_CLIENT,
    UPDATE_CURRENT_USER,
    RESET_CURRENT_CLIENT
 
}